// Comprehensive list of all countries with flags and search functionality
export interface Country {
  value: string
  label: string
  flag: string
  code: string
}

export const countries: Country[] = [
  { value: 'Afghanistan', label: 'Afghanistan', flag: '🇦🇫', code: 'AF' },
  { value: 'Albania', label: 'Albania', flag: '🇦🇱', code: 'AL' },
  { value: 'Algeria', label: 'Algeria', flag: '🇩🇿', code: 'DZ' },
  { value: 'Andorra', label: 'Andorra', flag: '🇦🇩', code: 'AD' },
  { value: 'Angola', label: 'Angola', flag: '🇦🇴', code: 'AO' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda', flag: '🇦🇬', code: 'AG' },
  { value: 'Argentina', label: 'Argentina', flag: '🇦🇷', code: 'AR' },
  { value: 'Armenia', label: 'Armenia', flag: '🇦🇲', code: 'AM' },
  { value: 'Australia', label: 'Australia', flag: '🇦🇺', code: 'AU' },
  { value: 'Austria', label: 'Austria', flag: '🇦🇹', code: 'AT' },
  { value: 'Azerbaijan', label: 'Azerbaijan', flag: '🇦🇿', code: 'AZ' },
  { value: 'Bahamas', label: 'Bahamas', flag: '🇧🇸', code: 'BS' },
  { value: 'Bahrain', label: 'Bahrain', flag: '🇧🇭', code: 'BH' },
  { value: 'Bangladesh', label: 'Bangladesh', flag: '🇧🇩', code: 'BD' },
  { value: 'Barbados', label: 'Barbados', flag: '🇧🇧', code: 'BB' },
  { value: 'Belarus', label: 'Belarus', flag: '🇧🇾', code: 'BY' },
  { value: 'Belgium', label: 'Belgium', flag: '🇧🇪', code: 'BE' },
  { value: 'Belize', label: 'Belize', flag: '🇧🇿', code: 'BZ' },
  { value: 'Benin', label: 'Benin', flag: '🇧🇯', code: 'BJ' },
  { value: 'Bhutan', label: 'Bhutan', flag: '🇧🇹', code: 'BT' },
  { value: 'Bolivia', label: 'Bolivia', flag: '🇧🇴', code: 'BO' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina', flag: '🇧🇦', code: 'BA' },
  { value: 'Botswana', label: 'Botswana', flag: '🇧🇼', code: 'BW' },
  { value: 'Brazil', label: 'Brazil', flag: '🇧🇷', code: 'BR' },
  { value: 'Brunei', label: 'Brunei', flag: '🇧🇳', code: 'BN' },
  { value: 'Bulgaria', label: 'Bulgaria', flag: '🇧🇬', code: 'BG' },
  { value: 'Burkina Faso', label: 'Burkina Faso', flag: '🇧🇫', code: 'BF' },
  { value: 'Burundi', label: 'Burundi', flag: '🇧🇮', code: 'BI' },
  { value: 'Cambodia', label: 'Cambodia', flag: '🇰🇭', code: 'KH' },
  { value: 'Cameroon', label: 'Cameroon', flag: '🇨🇲', code: 'CM' },
  { value: 'Canada', label: 'Canada', flag: '🇨🇦', code: 'CA' },
  { value: 'Cape Verde', label: 'Cape Verde', flag: '🇨🇻', code: 'CV' },
  { value: 'Central African Republic', label: 'Central African Republic', flag: '🇨🇫', code: 'CF' },
  { value: 'Chad', label: 'Chad', flag: '🇹🇩', code: 'TD' },
  { value: 'Chile', label: 'Chile', flag: '🇨🇱', code: 'CL' },
  { value: 'China', label: 'China', flag: '🇨🇳', code: 'CN' },
  { value: 'Colombia', label: 'Colombia', flag: '🇨🇴', code: 'CO' },
  { value: 'Comoros', label: 'Comoros', flag: '🇰🇲', code: 'KM' },
  { value: 'Congo', label: 'Congo', flag: '🇨🇬', code: 'CG' },
  { value: 'Costa Rica', label: 'Costa Rica', flag: '🇨🇷', code: 'CR' },
  { value: 'Croatia', label: 'Croatia', flag: '🇭🇷', code: 'HR' },
  { value: 'Cuba', label: 'Cuba', flag: '🇨🇺', code: 'CU' },
  { value: 'Cyprus', label: 'Cyprus', flag: '🇨🇾', code: 'CY' },
  { value: 'Czech Republic', label: 'Czech Republic', flag: '🇨🇿', code: 'CZ' },
  { value: 'Denmark', label: 'Denmark', flag: '🇩🇰', code: 'DK' },
  { value: 'Djibouti', label: 'Djibouti', flag: '🇩🇯', code: 'DJ' },
  { value: 'Dominica', label: 'Dominica', flag: '🇩🇲', code: 'DM' },
  { value: 'Dominican Republic', label: 'Dominican Republic', flag: '🇩🇴', code: 'DO' },
  { value: 'Ecuador', label: 'Ecuador', flag: '🇪🇨', code: 'EC' },
  { value: 'Egypt', label: 'Egypt', flag: '🇪🇬', code: 'EG' },
  { value: 'El Salvador', label: 'El Salvador', flag: '🇸🇻', code: 'SV' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea', flag: '🇬🇶', code: 'GQ' },
  { value: 'Eritrea', label: 'Eritrea', flag: '🇪🇷', code: 'ER' },
  { value: 'Estonia', label: 'Estonia', flag: '🇪🇪', code: 'EE' },
  { value: 'Eswatini', label: 'Eswatini', flag: '🇸🇿', code: 'SZ' },
  { value: 'Ethiopia', label: 'Ethiopia', flag: '🇪🇹', code: 'ET' },
  { value: 'Fiji', label: 'Fiji', flag: '🇫🇯', code: 'FJ' },
  { value: 'Finland', label: 'Finland', flag: '🇫🇮', code: 'FI' },
  { value: 'France', label: 'France', flag: '🇫🇷', code: 'FR' },
  { value: 'Gabon', label: 'Gabon', flag: '🇬🇦', code: 'GA' },
  { value: 'Gambia', label: 'Gambia', flag: '🇬🇲', code: 'GM' },
  { value: 'Georgia', label: 'Georgia', flag: '🇬🇪', code: 'GE' },
  { value: 'Germany', label: 'Germany', flag: '🇩🇪', code: 'DE' },
  { value: 'Ghana', label: 'Ghana', flag: '🇬🇭', code: 'GH' },
  { value: 'Greece', label: 'Greece', flag: '🇬🇷', code: 'GR' },
  { value: 'Grenada', label: 'Grenada', flag: '🇬🇩', code: 'GD' },
  { value: 'Guatemala', label: 'Guatemala', flag: '🇬🇹', code: 'GT' },
  { value: 'Guinea', label: 'Guinea', flag: '🇬🇳', code: 'GN' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau', flag: '🇬🇼', code: 'GW' },
  { value: 'Guyana', label: 'Guyana', flag: '🇬🇾', code: 'GY' },
  { value: 'Haiti', label: 'Haiti', flag: '🇭🇹', code: 'HT' },
  { value: 'Honduras', label: 'Honduras', flag: '🇭🇳', code: 'HN' },
  { value: 'Hungary', label: 'Hungary', flag: '🇭🇺', code: 'HU' },
  { value: 'Iceland', label: 'Iceland', flag: '🇮🇸', code: 'IS' },
  { value: 'India', label: 'India', flag: '🇮🇳', code: 'IN' },
  { value: 'Indonesia', label: 'Indonesia', flag: '🇮🇩', code: 'ID' },
  { value: 'Iran', label: 'Iran', flag: '🇮🇷', code: 'IR' },
  { value: 'Iraq', label: 'Iraq', flag: '🇮🇶', code: 'IQ' },
  { value: 'Ireland', label: 'Ireland', flag: '🇮🇪', code: 'IE' },
  { value: 'Israel', label: 'Israel', flag: '🇮🇱', code: 'IL' },
  { value: 'Italy', label: 'Italy', flag: '🇮🇹', code: 'IT' },
  { value: 'Jamaica', label: 'Jamaica', flag: '🇯🇲', code: 'JM' },
  { value: 'Japan', label: 'Japan', flag: '🇯🇵', code: 'JP' },
  { value: 'Jordan', label: 'Jordan', flag: '🇯🇴', code: 'JO' },
  { value: 'Kazakhstan', label: 'Kazakhstan', flag: '🇰🇿', code: 'KZ' },
  { value: 'Kenya', label: 'Kenya', flag: '🇰🇪', code: 'KE' },
  { value: 'Kiribati', label: 'Kiribati', flag: '🇰🇮', code: 'KI' },
  { value: 'Kuwait', label: 'Kuwait', flag: '🇰🇼', code: 'KW' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG' },
  { value: 'Laos', label: 'Laos', flag: '🇱🇦', code: 'LA' },
  { value: 'Latvia', label: 'Latvia', flag: '🇱🇻', code: 'LV' },
  { value: 'Lebanon', label: 'Lebanon', flag: '🇱🇧', code: 'LB' },
  { value: 'Lesotho', label: 'Lesotho', flag: '🇱🇸', code: 'LS' },
  { value: 'Liberia', label: 'Liberia', flag: '🇱🇷', code: 'LR' },
  { value: 'Libya', label: 'Libya', flag: '🇱🇾', code: 'LY' },
  { value: 'Liechtenstein', label: 'Liechtenstein', flag: '🇱🇮', code: 'LI' },
  { value: 'Lithuania', label: 'Lithuania', flag: '🇱🇹', code: 'LT' },
  { value: 'Luxembourg', label: 'Luxembourg', flag: '🇱🇺', code: 'LU' },
  { value: 'Madagascar', label: 'Madagascar', flag: '🇲🇬', code: 'MG' },
  { value: 'Malawi', label: 'Malawi', flag: '🇲🇼', code: 'MW' },
  { value: 'Malaysia', label: 'Malaysia', flag: '🇲🇾', code: 'MY' },
  { value: 'Maldives', label: 'Maldives', flag: '🇲🇻', code: 'MV' },
  { value: 'Mali', label: 'Mali', flag: '🇲🇱', code: 'ML' },
  { value: 'Malta', label: 'Malta', flag: '🇲🇹', code: 'MT' },
  { value: 'Marshall Islands', label: 'Marshall Islands', flag: '🇲🇭', code: 'MH' },
  { value: 'Mauritania', label: 'Mauritania', flag: '🇲🇷', code: 'MR' },
  { value: 'Mauritius', label: 'Mauritius', flag: '🇲🇺', code: 'MU' },
  { value: 'Mexico', label: 'Mexico', flag: '🇲🇽', code: 'MX' },
  { value: 'Micronesia', label: 'Micronesia', flag: '🇫🇲', code: 'FM' },
  { value: 'Moldova', label: 'Moldova', flag: '🇲🇩', code: 'MD' },
  { value: 'Monaco', label: 'Monaco', flag: '🇲🇨', code: 'MC' },
  { value: 'Mongolia', label: 'Mongolia', flag: '🇲🇳', code: 'MN' },
  { value: 'Montenegro', label: 'Montenegro', flag: '🇲🇪', code: 'ME' },
  { value: 'Morocco', label: 'Morocco', flag: '🇲🇦', code: 'MA' },
  { value: 'Mozambique', label: 'Mozambique', flag: '🇲🇿', code: 'MZ' },
  { value: 'Myanmar', label: 'Myanmar', flag: '🇲🇲', code: 'MM' },
  { value: 'Namibia', label: 'Namibia', flag: '🇳🇦', code: 'NA' },
  { value: 'Nauru', label: 'Nauru', flag: '🇳🇷', code: 'NR' },
  { value: 'Nepal', label: 'Nepal', flag: '🇳🇵', code: 'NP' },
  { value: 'Netherlands', label: 'Netherlands', flag: '🇳🇱', code: 'NL' },
  { value: 'New Zealand', label: 'New Zealand', flag: '🇳🇿', code: 'NZ' },
  { value: 'Nicaragua', label: 'Nicaragua', flag: '🇳🇮', code: 'NI' },
  { value: 'Niger', label: 'Niger', flag: '🇳🇪', code: 'NE' },
  { value: 'Nigeria', label: 'Nigeria', flag: '🇳🇬', code: 'NG' },
  { value: 'North Korea', label: 'North Korea', flag: '🇰🇵', code: 'KP' },
  { value: 'North Macedonia', label: 'North Macedonia', flag: '🇲🇰', code: 'MK' },
  { value: 'Norway', label: 'Norway', flag: '🇳🇴', code: 'NO' },
  { value: 'Oman', label: 'Oman', flag: '🇴🇲', code: 'OM' },
  { value: 'Pakistan', label: 'Pakistan', flag: '🇵🇰', code: 'PK' },
  { value: 'Palau', label: 'Palau', flag: '🇵🇼', code: 'PW' },
  { value: 'Palestine', label: 'Palestine', flag: '🇵🇸', code: 'PS' },
  { value: 'Panama', label: 'Panama', flag: '🇵🇦', code: 'PA' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea', flag: '🇵🇬', code: 'PG' },
  { value: 'Paraguay', label: 'Paraguay', flag: '🇵🇾', code: 'PY' },
  { value: 'Peru', label: 'Peru', flag: '🇵🇪', code: 'PE' },
  { value: 'Philippines', label: 'Philippines', flag: '🇵🇭', code: 'PH' },
  { value: 'Poland', label: 'Poland', flag: '🇵🇱', code: 'PL' },
  { value: 'Portugal', label: 'Portugal', flag: '🇵🇹', code: 'PT' },
  { value: 'Qatar', label: 'Qatar', flag: '🇶🇦', code: 'QA' },
  { value: 'Romania', label: 'Romania', flag: '🇷🇴', code: 'RO' },
  { value: 'Russia', label: 'Russia', flag: '🇷🇺', code: 'RU' },
  { value: 'Rwanda', label: 'Rwanda', flag: '🇷🇼', code: 'RW' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis', flag: '🇰🇳', code: 'KN' },
  { value: 'Saint Lucia', label: 'Saint Lucia', flag: '🇱🇨', code: 'LC' },
  { value: 'Saint Vincent and the Grenadines', label: 'Saint Vincent and the Grenadines', flag: '🇻🇨', code: 'VC' },
  { value: 'Samoa', label: 'Samoa', flag: '🇼🇸', code: 'WS' },
  { value: 'San Marino', label: 'San Marino', flag: '🇸🇲', code: 'SM' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe', flag: '🇸🇹', code: 'ST' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia', flag: '🇸🇦', code: 'SA' },
  { value: 'Senegal', label: 'Senegal', flag: '🇸🇳', code: 'SN' },
  { value: 'Serbia', label: 'Serbia', flag: '🇷🇸', code: 'RS' },
  { value: 'Seychelles', label: 'Seychelles', flag: '🇸🇨', code: 'SC' },
  { value: 'Sierra Leone', label: 'Sierra Leone', flag: '🇸🇱', code: 'SL' },
  { value: 'Singapore', label: 'Singapore', flag: '🇸🇬', code: 'SG' },
  { value: 'Slovakia', label: 'Slovakia', flag: '🇸🇰', code: 'SK' },
  { value: 'Slovenia', label: 'Slovenia', flag: '🇸🇮', code: 'SI' },
  { value: 'Solomon Islands', label: 'Solomon Islands', flag: '🇸🇧', code: 'SB' },
  { value: 'Somalia', label: 'Somalia', flag: '🇸🇴', code: 'SO' },
  { value: 'South Africa', label: 'South Africa', flag: '🇿🇦', code: 'ZA' },
  { value: 'South Korea', label: 'South Korea', flag: '🇰🇷', code: 'KR' },
  { value: 'South Sudan', label: 'South Sudan', flag: '🇸🇸', code: 'SS' },
  { value: 'Spain', label: 'Spain', flag: '🇪🇸', code: 'ES' },
  { value: 'Sri Lanka', label: 'Sri Lanka', flag: '🇱🇰', code: 'LK' },
  { value: 'Sudan', label: 'Sudan', flag: '🇸🇩', code: 'SD' },
  { value: 'Suriname', label: 'Suriname', flag: '🇸🇷', code: 'SR' },
  { value: 'Sweden', label: 'Sweden', flag: '🇸🇪', code: 'SE' },
  { value: 'Switzerland', label: 'Switzerland', flag: '🇨🇭', code: 'CH' },
  { value: 'Syria', label: 'Syria', flag: '🇸🇾', code: 'SY' },
  { value: 'Taiwan', label: 'Taiwan', flag: '🇹🇼', code: 'TW' },
  { value: 'Tajikistan', label: 'Tajikistan', flag: '🇹🇯', code: 'TJ' },
  { value: 'Tanzania', label: 'Tanzania', flag: '🇹🇿', code: 'TZ' },
  { value: 'Thailand', label: 'Thailand', flag: '🇹🇭', code: 'TH' },
  { value: 'Timor-Leste', label: 'Timor-Leste', flag: '🇹🇱', code: 'TL' },
  { value: 'Togo', label: 'Togo', flag: '🇹🇬', code: 'TG' },
  { value: 'Tonga', label: 'Tonga', flag: '🇹🇴', code: 'TO' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago', flag: '🇹🇹', code: 'TT' },
  { value: 'Tunisia', label: 'Tunisia', flag: '🇹🇳', code: 'TN' },
  { value: 'Turkey', label: 'Turkey', flag: '🇹🇷', code: 'TR' },
  { value: 'Turkmenistan', label: 'Turkmenistan', flag: '🇹🇲', code: 'TM' },
  { value: 'Tuvalu', label: 'Tuvalu', flag: '🇹🇻', code: 'TV' },
  { value: 'Uganda', label: 'Uganda', flag: '🇺🇬', code: 'UG' },
  { value: 'Ukraine', label: 'Ukraine', flag: '🇺🇦', code: 'UA' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates', flag: '🇦🇪', code: 'AE' },
  { value: 'United Kingdom', label: 'United Kingdom', flag: '🇬🇧', code: 'GB' },
  { value: 'United States', label: 'United States', flag: '🇺🇸', code: 'US' },
  { value: 'Uruguay', label: 'Uruguay', flag: '🇺🇾', code: 'UY' },
  { value: 'Uzbekistan', label: 'Uzbekistan', flag: '🇺🇿', code: 'UZ' },
  { value: 'Vanuatu', label: 'Vanuatu', flag: '🇻🇺', code: 'VU' },
  { value: 'Vatican City', label: 'Vatican City', flag: '🇻🇦', code: 'VA' },
  { value: 'Venezuela', label: 'Venezuela', flag: '🇻🇪', code: 'VE' },
  { value: 'Vietnam', label: 'Vietnam', flag: '🇻🇳', code: 'VN' },
  { value: 'Yemen', label: 'Yemen', flag: '🇾🇪', code: 'YE' },
  { value: 'Zambia', label: 'Zambia', flag: '🇿🇲', code: 'ZM' },
  { value: 'Zimbabwe', label: 'Zimbabwe', flag: '🇿🇼', code: 'ZW' }
]

// Search function for countries
export const searchCountries = (query: string): Country[] => {
  if (!query.trim()) return countries
  
  const lowercaseQuery = query.toLowerCase()
  return countries.filter(country => 
    country.label.toLowerCase().includes(lowercaseQuery) ||
    country.value.toLowerCase().includes(lowercaseQuery) ||
    country.code.toLowerCase().includes(lowercaseQuery)
  )
}

// Get country by value
export const getCountryByValue = (value: string): Country | undefined => {
  return countries.find(country => country.value === value)
}
